import { test, expect } from "@playwright/test";

/**
 * Generated by /10x-e2e from test-plan.md §3 Phase 4 (Risk #3, persistence).
 * Modeled on the seed exemplar (e2e/seed.spec.ts); auth via storageState.
 *
 * Risk: "A transaction save reports success but persists wrong or partial state."
 * Browser-level because it crosses auth → API → DB → SSR render → reload, and the
 * Phase-4 goal requires the result to show in BOTH portfolio views.
 *
 * "Both views" in this app, both on /dashboard:
 *   - summary/allocation view → AssetAllocationChart legend (role: listitem)
 *   - per-asset detail view   → PortfolioTable (role: cell), expandable per location
 *
 * The assertion fails if the risk materializes: if the deposit did not persist, the
 * asset is absent from both views after a real reload (verified by deliberate break).
 */
test("a recorded deposit persists and appears in both portfolio views after reload", async ({ page }) => {
  // Unique location (anti-pattern #5 defense) — parallel/re-run safe, and a per-run
  // marker the detail view can assert on even though USDT may pre-exist from prior runs.
  const location = `E2E ${Date.now()}`;
  const amount = "100";

  await page.goto("/dashboard");

  // --- entry: record a USDT deposit (stablecoin → no cost-basis price needed)
  await page.getByRole("button", { name: "Add Transaction" }).click();
  await expect(page.getByRole("heading", { name: "New Transaction" })).toBeVisible();

  await page.getByRole("tab", { name: "Deposit" }).click();
  await page.getByLabel("Amount", { exact: true }).fill(amount);

  // AssetAutocomplete is a popover: open it, type, pick the option.
  await page.getByRole("button", { name: "Search asset..." }).click();
  await page.getByPlaceholder("Search asset...").fill("USDT");
  await page.getByRole("option", { name: /USDT/i }).first().click();

  await page.getByLabel("Location", { exact: true }).fill(location);
  await page.getByRole("button", { name: "Save Transaction" }).click();

  // Wait for state, not time: the dialog closes once the save succeeds.
  await expect(page.getByRole("heading", { name: "New Transaction" })).toBeHidden();

  // --- the risk: after a real SSR reload, the position survives AND renders in BOTH views
  await page.reload();

  // View 1 — summary/allocation: USDT appears in the allocation legend (a listitem).
  await expect(page.getByRole("listitem").filter({ hasText: "USDT" }).first()).toBeVisible();

  // View 2 — per-asset detail table: USDT row, expandable to this run's unique location.
  const usdtCell = page.getByRole("cell", { name: "USDT" });
  await expect(usdtCell).toBeVisible();
  await usdtCell.click(); // expand the consolidated row to its per-location breakdown
  await expect(page.getByRole("cell", { name: location })).toBeVisible();
});
